# Generated by Django 2.0.5 on 2018-05-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(max_length=200)),
                ('registration_no', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date_published')),
                ('student_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
