# Generated by Django 2.0.5 on 2018-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_auto_20180517_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
